[package]
edition = "2021"
name = "filesystem_in_a_file"
version = "0.1.0"

[dependencies]
derive_builder = "0.12"
memmap = {version = "0.7", optional = true}
nix = "0.26"
tar = {version = "0.4", optional = true}
walkdir = "2"
xattr = "1"

[features]
default = ["tar"]
tar = ["dep:tar", "dep:memmap"]

[dev-dependencies]
tempfile = "3.3"
