[package]
edition = "2021"
name = "virtual_filesystem"
version = "0.1.0"

[dependencies]
derive_builder = "0.12"
nix = "0.26"
tar = {version = "0.4", optional = true}
thiserror = {version = "1", optional = true}

[features]
tar = ["dep:tar", "dep:thiserror"]
